# Kitty config: the recomended terminal emulator for hyprland
background_opacity 0.7
enable_audio_bell no

disable_ligatures never
# don't try to set the background blur in here, control it in the hyprland
# config

# BEGIN_KITTY_FONTS
font_family      family='Iosevka Term' postscript_name=Iosevka-Term-Semibold-Extended
bold_font        family='Iosevka Term' style='Bold Extended'
italic_font      family='Iosevka Term' style='Semibold Extended Italic'
bold_italic_font family='Iosevka Term' style='Bold Extended Italic'
# END_KITTY_FONTS
