# This is the current active "theme"

# Refer to https://wiki.hyprland.org/Configuring/Variables/

$WALLPAPER_PATH = ~/Pictures/wallpapers/nausicaa01.png

$HIGHLIGHT_COLOR = rgba(f4ba51ff)
$MAIN_COLOR = rgba(33bbffff)

$SHADOW_COLOR = rgba(1a1a1aee)

