preload = ~/Pictures/wallpapers/nausicaa01.png

# , means set all wallpapers
# wallpaper = , ~/Pictures/wallpapers/nausicaa01.png
splash=false

wallpaper {
    monitor =
    path = ~/Pictures/wallpapers/nausicaa01.png
}

