source = ~/.config/hypr/myColors.conf

label {
    monitor =
    # text = cmd[update:1000] echo "<span foreground='##ff2222'>$(date)</span>"
    text = cmd[update:1000] echo $TIME12
    color = rgb(255, 255, 255, 1.0)
    position = 0, 50
    font_size = 64
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = $BLU $YEL 15deg
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 15

    position = 0, -50
    halign = center
    valign = center
}

background {
    monitor =
    path = ~/Pictures/wallpapers/nausicaa01.png
    # should tweak the colors probably
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2
}

