##########################
### MY HYPRLAND CONFIG ###
##########################

# this is mostly stolen from one of the defaults, but I'm making lots of little
# changes for quality of life, most importantly, breaking the most likely to be
# edited/longest config "sections" into thir own files.

# The wiki, in case you're as lazy as I am
# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# NOTE last auto is auto scale, can cause lots of apps to be ugly
# Make all monitors mirror builtin (need to fix later)
monitor = , preferred, auto, 1, mirror, eDP-1 

# Woo hoo! thank you mr. reddit man
# https://www.reddit.com/r/hyprland/comments/1idkd00/app_not_scaling_properly_in_hyprland/
# Makes non-native apps NOT scale at all
xwayland {
    enabled = true
    force_zero_scaling = true
}

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


#############################
### EXTERNAL CONFIG FILES ###
#############################

# breaking apart conf files makes development much easier, and folder much
# cleaner
source = ~/.config/hypr/configs/autostarts.conf
source = ~/.config/hypr/configs/lookAndFeel.conf
source = ~/.config/hypr/configs/inputAndKeybindings.conf


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
