#################
### AUTOSTART ###
#################

# wallpaper engine startup
exec-once = hyprpaper

# waybar startup script, should detect changes to config and restart
# This script is in my .local/bin/scripts path, with all of my other scripts
exec-once = waybar-autoreload

# Hyprland's default "idle manageer"
# for locking the screen
exec-once = hypridle
