#################
### AUTOSTART ###
#################

# wallpaper engine startup
exec-once = hyprpaper

# waybar startup script, should detect changes to config and restart
# This script is in my .local/bin path, with all of my other scripts
exec-once = waybar-autoreload
