#################
### AUTOSTART ###
#################

# wallpaper engine startup
exec-once = hyprpaper

# waybar startup script, should detect changes to config and restart
# This script is in my .local/bin/scripts path, with all of my other scripts
exec-once = waybar-autoreload

# Hyprland's default "idle manageer"
# for locking the screen when idle
exec-once = hypridle

# notificaton daemon
exec-once = dunst

# monitor config autochange on configuration chage
# (so laptop dock dynamically changes)
exec-once = kanshi

# night-shift color filter
exec-once = hyprsunset
