#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    touchpad {
        natural_scroll = false
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = false
}

####################
### KEYBINDINGSS ###
####################

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as mod key

# Many of my keybinds are simmilar to DWM's defaults
# DWM was my first minimal WM without a DE
# it was too bare bones for me, and would've taken too much ricing
bind = $mainMod, W, exec, $WEB_BROWSER
bind = $mainMod SHIFT, W, exec, OpenWebBookmarks

bind = $mainMod SHIFT, RETURN, exec, $TERMINAL # uses environment variable
bind = $mainMod SHIFT, C, killactive,
bind = $mainMod, E, exec, $FILE_MANAGER

bind = $mainMod, SPACE, exec, $LAUNCHER

# Must use SHIFT L for lock because SUPER + L is for window focus changing
bind = $mainMod SHIFT, L, exec, hyprlock

bind = $mainMod, V, togglefloating,
# bind = $mainMod, P, pseudo, # dwindle

# binde allows for repeating when held
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = ,XF86AudioMicMute, exec, pactl -- set-source-mute 0 toggle

# Monitor brightness control, needs brightnessctl installed
binde = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-
binde = ,XF86MonBrightnessUp, exec, brightnessctl s +10%

# shift for fine grained brightness control
binde = SHIFT,XF86MonBrightnessDown, exec, brightnessctl s 1%-
binde = SHIFT,XF86MonBrightnessUp, exec, brightnessctl s +1%

# COMPLETELY EXITS HYPRLAND, goes back to SDDM
# TODO should probably make an "are you sure" promp somehow?
bind = $mainMod, M, exit,

# Move focus with mainMod + vim keybinds
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Example special workspace (scratchpad)
# MOD+S opens scratchpad
# MOD+SHIFT+S moves curr to scratchpad
# can use MOD+SHIFT+N to move from scratchpad to workspace N
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
