#####################
### LOOK AND FEEL ###
#####################

# Pull in my colors

# This file containes all variables and settings I'll want to tweak for
# different color schemes/wallpapers. 

# Settings in THIS file (lookandfeel.conf) I probably won't tweak across
# different colorschemes

source = ~/.cache/wal/hyprlandColors.conf

$BORDER_RADIUS = 10
$BORDER_THICKNESS = 2


# https://wiki.hyprland.org/Configuring/Variables/#general
general { 
    gaps_in = 2  # gaps between windows
    gaps_out = 6

    border_size = $BORDER_THICKNESS

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = $HIGHLIGHT_COLOR $MAIN_COLOR 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false 

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = $BORDER_RADIUS

    # Change transparency of focused and unfocused windows
    # I don't like this anymore
    # active_opacity = 1.0
    # inactive_opacity = 0.925

    # Its really subtle, but it adds a shadow around active
    # really big too, covers other windows but isn't obtrusive
    # https://www.reddit.com/r/hyprland/comments/1c8swla/shadows_in_hyprland/
    shadow {
        enabled = true
        range = 200
        render_power = 4
        scale=0.9
        offset = 10 10
        color = rgba(101010af)
        color_inactive = rgba(0, 0, 0, 0)
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 5
        passes = 1 
        vibrancy = 0.1696
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = true

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    preserve_split = true # Hyprland says you probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}


# I'll add this sooner or later
# layerrule {
#     name = waybar
#     blur = on
#     blur_popups = on
#     match:namespace = waybar
# }

# Disable rounding and border on fullscreen apps
windowrule {
    name = Fullscreen
    match:fullscreen = true
    rounding = 0
    border_size = 0
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc { 
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}
