###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$webBrowser = firefox
$editor = vim

# This is a script in ~/.local/bin/scripts
# Tells rofi how to launch, rather than having a large line here
$appLauncher = rofi_launch

env = EDITOR,$editor
env = TERMINAL,$terminal
env = FILE_MANAGER,$fileManager
env = WEB_BROWSER,$webBrowser
